version: '3.9'

services:
  app:
    build:
      context: .
    container_name: app
    restart: always
    env_file:
      - .env


  nginx:
    build:
      context: ./docker/proxy
    container_name: nginx
    restart: always
    depends_on:
      - app
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - certbot-web:/vol/www
      - proxy-dhparams:/vol/nginx
      - certbot-certs:/etc/letsencrypt
    env_file:
      - .env


  certbot:
    build:
      context: ./docker/certbot
    container_name: certbot
    command: echo "Skipping ..."
    env_file:
      - .env
    volumes:
      - certbot-web:/vol/www
      - certbot-certs:/etc/letsencrypt
    depends_on:
      - nginx

volumes:
  certbot-web:
  proxy-dhparams:
  certbot-certs: