version: '3.9'

services:
  web:
    build:
      context: .
    container_name: web
    restart: always
    command: sh -c "python manage.py makemigrations && 
            "
      - 
      - python manage.py migrate
      - python manage.py runserver
    volumes:
      - .:/app
      - static_files:/app/staticfiles
      - static:/app/static
      - media:/app/media
    env_file:
      - .env

  redis:
    container_name: erp_redis
    image: redis:alpine
    ports:
      - 6379:6379
    depends_on:
      - web


  celery-worker:
    container_name: erp_celery_worker
    restart: always
    build:
      context: .
    command: celery -A config worker -l info
    volumes:
      - .:/web
    depends_on:
      - web
      - redis


  celery-beat:
    container_name: erp_celery_beat
    restart: always
    build:
      context: .
    command: celery -A config beat -l info
    volumes:
      - .:/web
    depends_on:
      - web
      - redis
      - celery-worker


volumes:
  static_files:
  static:
  media:

