version: '3.9'

services:
  web:
    build:
      context: .
    container_name: web
    restart: always
    volumes:
      - .:/app
      - static_files:/app/staticfiles
      - static:/app/static
      - media:/app/media
      - /tmp/app/mysqld:/run/mysqld
    env_file:
      - .env
    depends_on:
      - mysql


  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      # - ./certbot/www:/var/www/certbot/:ro
      - static_files:/home/app/staticfiles/
      - static:/home/app/static/
      - media:/home/app/media/
    depends_on:
      - web
    ports:
      - 1080:80
      - 1443:443
    env_file:
      - .env


  # certbot:
  #   image: certbot/certbot:latest
  #   container_name: certbot
  #   volumes:
  #     - ./certbot/www/:/var/www/certbot/:rw


  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - /tmp/app/mysqld:/var/run/mysqld
      - ./erp_mysql:/var/lib/mysql
    ports:
      - 3307:3306


  redis:
    container_name: erp_redis
    image: redis:alpine
    ports:
      - 6379:6379
    depends_on:
      - mysql
      - web


  celery-worker:
    container_name: erp_celery_worker
    restart: always
    build:
      context: .
    command: celery -A config worker -l info
    volumes:
      - .:/web
    depends_on:
      - web
      - redis
      - mysql


  celery-beat:
    container_name: erp_celery_beat
    restart: always
    build:
      context: .
    command: celery -A config beat -l info
    volumes:
      - .:/web
    depends_on:
      - web
      - redis
      - celery-worker
      - mysql


volumes:
  static_files:
  static:
  media:

