REPORT_FIELDS = {
    'contract': {
        'category_manager': "Category manager",
        'contract_owner': "Contract owner",
        'lawyer': "Lawyer",
        'project_owner': "Project owner",
        'creation_date': "Created date",
        'effective_date': "Effective date",
        'expiration_date': "Expiration date",
        'duration': "Duration",
        'name': "Name",
        'contract_number': "Contract number",
        'description': "Description",
        'parent_agreement': "Parent agreement",
        'departement': "Departement",
        'contract_structure': "Contract structure",
        'contract_amount': "Contract amount",
        'category': "Category",
        'currency': "Currency",
        'organization': "organization",
        'create_by': "Created by",
        'terms': "Terms",
        'contract_notice': "Contract notice",
        'amendment': "Amendment",
        'status': "Status",
        'count_changes': "Count changes",
        'notification': "Notification",
        'supplier': "Supplier",
        'serviceCommodityConsultant': {
            'services': 'Services',
            'commodities': 'Commodities',
            'consultants': 'Consultants'
        }
    },
    'user': {
        'email': 'Email',
        'phone': 'Phone',
        'first_name': 'First name',
        'last_name': 'Last name',
        'street': 'street',
        'city': 'city',
        'country': 'country',
        'role': 'role',
    },
    'service': {
        'creator': 'Created by',
        'name': 'Name',
        'description': 'Description',
        'frequency': 'Frequency',
        'must_increase': 'Must increase',
        'increasePayTerms': 'Increase pay terms',
        'how_many_times': 'How many times',
        'growthPercentage': 'Growth percentage',
        'status': 'Status',
        'created_at': 'Created date',
    }
}
